import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const root = process.cwd(), site = 'https://findost.io', out = join(root, 'public');
const esc = (s = '') => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const date = (s) => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'Asia/Kolkata' }).format(new Date(`${s}T00:00:00+05:30`));
function article(raw, slug) {
  const [, front, body] = raw.match(/^---\s*\r?\n([\s\S]*?)\r?\n---\s*\r?\n([\s\S]*)$/) || [];
  if (!front) throw new Error(`Invalid front matter: ${slug}`);
  const meta = Object.fromEntries(front.split(/\r?\n/).map((x) => { const i = x.indexOf(':'); return [x.slice(0, i).trim(), x.slice(i + 1).trim().replace(/^['"]|['"]$/g, '')]; }));
  return { slug, ...meta, body: body.trim() };
}
function markdown(md) {
  let list = false;
  const finish = () => { const value = list ? '</ul>' : ''; list = false; return value; };
  return md.split(/\r?\n/).map((line) => {
    if (/^[-*] |^\d+\. /.test(line)) { if (!list) { list = true; return `<ul><li>${inline(line.replace(/^([-*]|\d+\.) /, ''))}</li>`; } return `<li>${inline(line.replace(/^([-*]|\d+\.) /, ''))}</li>`; }
    if (/^## /.test(line)) return `${finish()}<h2>${esc(line.slice(3))}</h2>`;
    if (/^### /.test(line)) return `${finish()}<h3>${esc(line.slice(4))}</h3>`;
    return line.trim() ? `${finish()}<p>${inline(line)}</p>` : finish();
  }).join('') + finish();
}
function inline(s) { return esc(s).replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>'); }
function page({ title, description, canonical, schema, body }) {
  return `<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Findost</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><meta name="robots" content="index,follow,max-snippet:-1,max-image-preview:large"><meta property="og:type" content="article"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><script type="application/ld+json">${JSON.stringify(schema)}</script><style>:root{--p:#5f29ea;--ink:#111827;--muted:#586174;--line:#e5e7eb;--bg:#fafafa}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.7 Arial,sans-serif}a{color:var(--p);text-decoration:none}.shell{max-width:1040px;margin:auto;padding:0 24px}.nav{height:68px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between}.brand{font-weight:800;font-size:22px;color:var(--ink)}.brand span{color:var(--p)}.nav a{font-weight:600;margin-left:20px}.hero{padding:64px 0 40px}.label{font-size:13px;color:var(--p);font-weight:700;letter-spacing:.08em;text-transform:uppercase}.hero h1{font-size:clamp(32px,5vw,52px);line-height:1.12;max-width:800px;margin:12px 0}.lead{font-size:19px;color:var(--muted);max-width:700px}.meta{font-size:14px;color:var(--muted)}main{max-width:760px;margin:auto;padding:0 24px 72px}main h2{font-size:28px;line-height:1.25;margin-top:38px}main h3{font-size:21px}main p,main li{font-size:17px}main li{margin:8px 0}.answer{background:#ede8ff;border-left:4px solid var(--p);padding:20px 22px;margin:28px 0;border-radius:8px}.disclaimer{font-size:14px;color:var(--muted);border-top:1px solid var(--line);padding-top:20px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px;padding-bottom:64px}.card{display:block;background:#fff;border:1px solid var(--line);border-radius:14px;padding:24px;color:var(--ink)}.card:hover{box-shadow:0 8px 28px #00000012}.card h2{font-size:21px;line-height:1.3;margin:10px 0}.card p{color:var(--muted);font-size:15px}.footer{border-top:1px solid var(--line);padding:30px 0;color:var(--muted);font-size:14px}</style></head><body><header class="nav"><div class="shell nav"><a class="brand" href="/">find<span>ost</span></a><nav><a href="/">Home</a><a href="/blog/">Blog</a><a href="https://wa.me/916205247092" rel="noopener">Talk to us</a></nav></div></header>${body}<footer class="footer"><div class="shell">© Findost Financial Technologies Pvt. Ltd. Educational content only; not investment advice. Mutual fund investments are subject to market risks.</div></footer></body></html>`;
}
const dir = join(root, 'content', 'blog');
const articles = (await Promise.all((await readdir(dir)).filter((f) => f.endsWith('.md')).map(async (f) => article(await readFile(join(dir, f), 'utf8'), f.slice(0, -3))))).sort((a, b) => b.date.localeCompare(a.date));
await rm(out, { recursive: true, force: true }); await mkdir(join(out, 'blog'), { recursive: true });
await writeFile(join(out, 'index.html'), await readFile(join(root, 'findost_io.html'), 'utf8'));
const links = articles.map((a) => `${site}/blog/${a.slug}/`);
const cards = articles.map((a) => `<a class="card" href="/blog/${a.slug}/"><div class="label">Investor education</div><h2>${esc(a.title)}</h2><p>${esc(a.description)}</p><div class="meta">${date(a.date)} · 6 min read</div></a>`).join('');
await writeFile(join(out, 'blog', 'index.html'), page({ title: 'Blog', description: 'Plain-English money education for Indian investors.', canonical: `${site}/blog/`, schema: { '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'Findost Blog', mainEntity: { '@type': 'ItemList', itemListElement: links.map((url, i) => ({ '@type': 'ListItem', position: i + 1, url })) } }, body: `<div class="shell hero"><div class="label">Findost learning centre</div><h1>Clear answers for important money decisions.</h1><p class="lead">Independent, plain-English explainers for Indian investors. Every article is educational and reviewed before publication.</p></div><main class="shell"><div class="grid">${cards}</div></main>` }));
for (const a of articles) { const canonical = `${site}/blog/${a.slug}/`, schema = { '@context': 'https://schema.org', '@type': 'BlogPosting', headline: a.title, description: a.description, datePublished: a.date, dateModified: a.date, mainEntityOfPage: canonical, author: { '@type': 'Organization', name: 'Findost Editorial Team', url: site }, publisher: { '@type': 'Organization', name: 'Findost', url: site }, inLanguage: 'en-IN', about: ['Mutual funds', 'Personal finance', 'Indian investing'] }, target = join(out, 'blog', a.slug, 'index.html'); await mkdir(dirname(target), { recursive: true }); await writeFile(target, page({ title: a.title, description: a.description, canonical, schema, body: `<div class="shell hero"><div class="label">Investor education</div><h1>${esc(a.title)}</h1><p class="lead">${esc(a.description)}</p><p class="meta">Published ${date(a.date)} · By Findost Editorial Team</p></div><main><aside class="answer"><strong>Quick answer</strong><br>${esc(a.description)}</aside>${markdown(a.body)}<p class="disclaimer">This is educational information, not personalised investment advice or a solicitation. Consider your goals, risk tolerance and suitability before investing.</p></main>` })); }
const lastmod = new Date().toISOString().slice(0, 10), urls = [`${site}/`, `${site}/blog/`, ...links];
await writeFile(join(out, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map((u) => `<url><loc>${u}</loc><lastmod>${lastmod}</lastmod></url>`).join('')}</urlset>`);
await writeFile(join(out, 'robots.txt'), `User-agent: *\nAllow: /\n\nSitemap: ${site}/sitemap.xml\n`);
await writeFile(join(out, 'llms.txt'), `# Findost\n\n> Findost provides educational personal-finance content for Indian investors. Content is general information, not personalised investment advice.\n\n## Core pages\n\n- [Home](${site}/)\n- [Blog](${site}/blog/)\n\n## Articles\n\n${articles.map((a) => `- [${a.title}](${site}/blog/${a.slug}/): ${a.description}`).join('\n')}\n\n## Important\n\n- Educational content only; mutual fund investments are subject to market risks.\n- Verify time-sensitive figures, regulations and fund data against primary sources.\n`);
await writeFile(join(out, 'sitemap.md'), `# Findost site map\n\n## Main\n\n- [Home](${site}/)\n- [Blog](${site}/blog/)\n\n## Blog articles\n\n${articles.map((a) => `- [${a.title}](${site}/blog/${a.slug}/)`).join('\n')}\n`);
console.log(`Built ${articles.length} articles.`);
